services:

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: budgetok
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    image: ghcr.io/ognjenkl/budget-ok-web/frontend:latest
    ports:
      - "5173:80"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 10s
      timeout: 5s
      retries: 5

  bank-ok:
    image: ghcr.io/ognjenkl/bank-ok-repo/bank-ok:latest
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8081/api/expenses"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: ghcr.io/ognjenkl/budget-ok-backend/backend:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/budgetok
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      BANKOK_HOST: http://bank-ok:8080
    depends_on:
      db:
        condition: service_healthy
      bank-ok:
        condition: service_healthy

volumes:
  postgres_data: